### ISSUE TITLE
Make database models to store existing solution's data

### ISSUE THREAD

**Issue by JeremySanchez1** [uprm-inso4116-2023-2024-S1/semester-project-college-toolbox#36]

**Comment by JannGarcia** [comment]
Currently we are unaware of what solutions we would like to integrate with ([waiting for the form responses](https://github.com/uprm-inso4116-2023-2024-S1/semester-project-college-toolbox/issues/35)), so we can only generalize what data we would like to store on the database. 

For now, the model would be something along the lines of
* Application Name
* Application URL
* 
I'm not sure why we would need a database for this data however, since Google Forms generates a Google Sheet w/ everyone's responses. We can probably define the model a bit more once we start collecting responses.

**Comment by JannGarcia** [comment]
Created the Model here: https://docs.google.com/document/d/14OERp5tkYNZDkMTULdDf9czm8alKyFo9_tX3EcpGBFM/edit

Will be working on defining the model in the backend, and focus on populating it with sample data
